name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"  # Adjust this if your package.json is in a subdirectory
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt -y update
            sudo apt install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            sudo chown -R $USER:$USER /var/www/html
            sudo chmod -R 777 /var/www/html
            #rm -rf /var/www/html/build
            # mv build /var/www/html/
            #sudo rm -rf /var/www/html/*
            #cd /var/www/html/
            # Ensure package.json exists before proceeding
            if [ -f /var/www/html/package.json ]; then
            cd /var/www/html/
            rm -rf node_modules package-lock.json build/
            sudo cp -a ~/githubaction/public/  /var/www/html
            sudo cp -a ~/githubaction/src/  /var/www/html
            npm cache clean --force
            npm install --force
            npm audit fix 
            #mv build/* /var/www/html/
            npm run build

              # Move build files if the build directory exists
              if [ -d build ]; then
                sudo mv build/* /var/www/html/
              else
                echo "Error: Build directory does not exist."
                exit 1
              fi
            else
              echo "Error: package.json not found in /var/www/html."
              exit 1
            fi
            sudo npm start
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            #sudo systemctl restart apache2
